### ISSUE TITLE
Added variables text file, but black screen

### ISSUE THREAD

**Issue by crmeeds** [rfkinline/BTC-Dashboard#3]
Not sure what's going on. I added a "variables" text file to the location of the python script, ran the program, and black screen. Am I missing something?

**Comment by crmeeds** [comment]
Disregard, the issue was due to an error referencing the bitcoin image you also uploaded. After adding that in, I just have an issue with DefiPulse: "wrong or expired API key." Does this key need to be unique to me?

**Comment by rfkinline** [comment]
Yes,  The Defipulse API key is good for 1000 calls per month. I am working on a solution to solve this problem.
